$phpcode = "\$sql = \"select distinct locale from language where locale != 'All' order by locale\";";
$phpcode .= "\$modelList = \$dbDAO->executeQry(\$sql);";
$phpcode .= "\$modelList = convert2array(\$modelList);";
$phpcode .= "\$rv = split(\"XxX\",\$confModel->adminhtmltype);";
$phpcode .= "\$rkey = \"\";";
$phpcode .= "\$rval = \"\";";
$phpcode .= "if ( \$formAction != 'new' ) {";
$phpcode .= "\$sql = \"select * from language where id = '\".\$id.\"'\";";
$phpcode .= "\$tmpModel = \$dbDAO->executeQry(\$sql);";
$phpcode .= "\$rkey = \$tmpModel->resource_key;";
$phpcode .= "}";
$phpcode .= "echo \"<td>\".\$rv[0].\"  <input type='text' size='45' id='\".\$key.\"_\".\$rv[0].\"' name='\".\$key.\"_\".\$rv[0].\"' value='\".\$rkey.\"'></td></tr>\";";
$phpcode .= "foreach ( \$modelList as \$modelLst ) {";
$phpcode .= "if ( \$formAction != 'new' ) {";
$phpcode .= "\$sql = \"select * from language where resource_key = '\".\$rkey.\"' and locale = '\".\$modelLst->locale.\"'\";";
$phpcode .= "\$tmpModel = \$dbDAO->executeQry(\$sql);";
$phpcode .= "\$rval =  \$tmpModel->resource_value;";
$phpcode .= "}";
$phpcode .= "echo \"<tr><td valign='top'>\".\$modelLst->locale.\"</td><td> <textarea cols='50' rows='5' id='\".\$key.\"_\".\$modelLst->locale.\"' name='\".\$key.\"_\".\$modelLst->locale.\"'>\".\$rval.\"</textarea></td></tr>\";";
$phpcode .= "}";
